-- MySQL Script generated by MySQL Workbench
-- Fri May 17 13:55:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KeyB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KeyB` DEFAULT CHARACTER SET utf8;
USE `KeyB`;

-- -----------------------------------------------------
-- Table `KeyB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KeyB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `KeyB`.`dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KeyB`.`dictionary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `text` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `KeyB`.`texts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KeyB`.`texts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `KeyB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `KeyB`.`approach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KeyB`.`approach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL,
  `time` TIME NOT NULL,
  `idUser` INT NOT NULL,
  `idDict` INT NOT NULL,
  `idText` INT NOT NULL,
  `result` TINYINT NOT NULL,
  `inClass` TINYINT NOT NULL,
  `speed` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`idUser` ASC),
  INDEX `id_dictionary_idx` (`idDict` ASC),
  INDEX `id_text_idx` (`idText` ASC),
  CONSTRAINT `id_user_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `KeyB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_dictionary_fk`
    FOREIGN KEY (`idDict`)
    REFERENCES `KeyB`.`dictionary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_text_fk`
    FOREIGN KEY (`idText`)
    REFERENCES `KeyB`.`texts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;